"""link medication to drug catalogue, add dispensing state

Revision ID: 065182ce6b9a
Revises: c57a4dd17fc5
Create Date: 2026-09-21 07:58:21.377484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065182ce6b9a'
down_revision: Union[str, Sequence[str], None] = 'c57a4dd17fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicationchart', sa.Column('drug_id', sa.Integer(), nullable=True))
    op.add_column('medicationchart',
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('medicationchart',
    sa.Column('is_dispensed', sa.Boolean(), nullable=False, server_default='false'))

    op.create_index(op.f('ix_medicationchart_drug_id'), 'medicationchart', ['drug_id'], unique=False)
    op.create_index(op.f('ix_medicationchart_is_dispensed'), 'medicationchart', ['is_dispensed'], unique=False)
    op.create_foreign_key(None, 'medicationchart', 'drug', ['drug_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicationchart', type_='foreignkey')
    op.drop_index(op.f('ix_medicationchart_is_dispensed'), table_name='medicationchart')
    op.drop_index(op.f('ix_medicationchart_drug_id'), table_name='medicationchart')
    op.drop_column('medicationchart', 'is_dispensed')
    op.drop_column('medicationchart', 'quantity_dispensed')
    op.drop_column('medicationchart', 'drug_id')
    # ### end Alembic commands ###
