"""add password reset tokens

Revision ID: 8779294bf247
Revises: 9d421791f711
Create Date: 2026-07-23 17:09:24.140279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8779294bf247'
down_revision: Union[str, Sequence[str], None] = '9d421791f711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "passwordresettoken",
        "expires_at",
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "passwordresettoken",
        "expires_at",
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
