"""add clinical documents

Revision ID: 922b52aa2718
Revises: 5361aeee4406
Create Date: 2026-07-22 07:32:46.886253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '922b52aa2718'
down_revision: Union[str, Sequence[str], None] = '5361aeee4406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('attending_doctor', sa.Uuid(), nullable=False),
    sa.Column('encounter_date', sa.DateTime(), nullable=False),
    sa.Column('ward_clinic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['attending_doctor'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clerkingnote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('presenting_complaints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('history', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('examination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assessment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('investigations', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('treatment_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('follow_up', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dischargesummary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hospital_course', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discharge_medications', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('follow_up', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fluidbalance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('intake', sa.Float(), nullable=True),
    sa.Column('output', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicationchart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encouter_id', sa.Integer(), nullable=False),
    sa.Column('drug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('stop_date', sa.DateTime(), nullable=True),
    sa.Column('prescribed_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encouter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nursingassessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('chief_complaint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nursing_assessment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nursing_diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('care_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evaluation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedurenote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('indication', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('procedure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('findings', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('complications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progressnote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('subjective', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assessment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitalsigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('blood_pressure', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vitalsigns')
    op.drop_table('progressnote')
    op.drop_table('procedurenote')
    op.drop_table('nursingassessment')
    op.drop_table('medicationchart')
    op.drop_table('fluidbalance')
    op.drop_table('dischargesummary')
    op.drop_table('clerkingnote')
    op.drop_table('encounter')
    # ### end Alembic commands ###
