"""add drug inventory

Revision ID: c57a4dd17fc5
Revises: cdd5ce820366
Create Date: 2026-09-20 17:16:58.709798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c57a4dd17fc5'
down_revision: Union[str, Sequence[str], None] = 'cdd5ce820366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_category'), 'drug', ['category'], unique=False)
    op.create_index(op.f('ix_drug_generic'), 'drug', ['generic'], unique=False)
    op.create_index(op.f('ix_drug_name'), 'drug', ['name'], unique=False)
    op.create_index(op.f('ix_drug_needs_review'), 'drug', ['needs_review'], unique=False)
    op.create_index(op.f('ix_drug_search_name'), 'drug', ['search_name'], unique=False)
    op.create_table('stocktransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocktransaction_drug_id'), 'stocktransaction', ['drug_id'], unique=False)
    op.create_index(op.f('ix_stocktransaction_transaction_type'), 'stocktransaction', ['transaction_type'], unique=False)
    op.drop_table('investigation')
    op.drop_index(op.f('ix_amendment_document_id'), table_name='amendment')
    op.drop_index(op.f('ix_amendment_document_type'), table_name='amendment')
    op.drop_table('amendment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amendment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.uid'], name=op.f('amendment_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('amendment_pkey'))
    )
    op.create_index(op.f('ix_amendment_document_type'), 'amendment', ['document_type'], unique=False)
    op.create_index(op.f('ix_amendment_document_id'), 'amendment', ['document_id'], unique=False)
    op.create_table('investigation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clinical_information', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('examination_requested', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('results', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_completed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], name=op.f('investigation_encounter_id_fkey')),
    sa.ForeignKeyConstraint(['requested_by'], ['user.uid'], name=op.f('investigation_requested_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('investigation_pkey'))
    )
    op.drop_index(op.f('ix_stocktransaction_transaction_type'), table_name='stocktransaction')
    op.drop_index(op.f('ix_stocktransaction_drug_id'), table_name='stocktransaction')
    op.drop_table('stocktransaction')
    op.drop_index(op.f('ix_drug_search_name'), table_name='drug')
    op.drop_index(op.f('ix_drug_needs_review'), table_name='drug')
    op.drop_index(op.f('ix_drug_name'), table_name='drug')
    op.drop_index(op.f('ix_drug_generic'), table_name='drug')
    op.drop_index(op.f('ix_drug_category'), table_name='drug')
    op.drop_table('drug')
    # ### end Alembic commands ###
