"""add prescription codes

Revision ID: cdd5ce820366
Revises: b0a2938e2824
Create Date: 2026-09-09 10:49:39.541914

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'cdd5ce820366'
down_revision: Union[str, Sequence[str], None] = 'b0a2938e2824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_dispensed', sa.Boolean(), nullable=False),
    sa.Column('dispensed_by', sa.Uuid(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['dispensed_by'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_code'), 'prescription', ['code'], unique=True)
    op.create_index(op.f('ix_prescription_encounter_id'), 'prescription', ['encounter_id'], unique=False)
    op.drop_index(op.f('ix_amendment_document_id'), table_name='amendment')
    op.drop_index(op.f('ix_amendment_document_type'), table_name='amendment')
    op.drop_table('amendment')
    op.drop_table('investigation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clinical_information', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('examination_requested', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('results', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_completed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], name=op.f('investigation_encounter_id_fkey')),
    sa.ForeignKeyConstraint(['requested_by'], ['user.uid'], name=op.f('investigation_requested_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('investigation_pkey'))
    )
    op.create_table('amendment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.uid'], name=op.f('amendment_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('amendment_pkey'))
    )
    op.create_index(op.f('ix_amendment_document_type'), 'amendment', ['document_type'], unique=False)
    op.create_index(op.f('ix_amendment_document_id'), 'amendment', ['document_id'], unique=False)
    op.drop_index(op.f('ix_prescription_encounter_id'), table_name='prescription')
    op.drop_index(op.f('ix_prescription_code'), table_name='prescription')
    op.drop_table('prescription')
    # ### end Alembic commands ###
