"""add investigation

Revision ID: ed45e7f29403
Revises: f531c82942f5
Create Date: 2026-09-04 08:57:47.230556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ed45e7f29403'
down_revision: Union[str, Sequence[str], None] = 'f531c82942f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clinical_information', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('examination_requested', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('results', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_completed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], name=op.f('investigation_encounter_id_fkey')),
    sa.ForeignKeyConstraint(['requested_by'], ['user.uid'], name=op.f('investigation_requested_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('investigation_pkey'))
    )
    # ### end Alembic commands ###
