"""add workflow_status to encounter

Revision ID: f531c82942f5
Revises: ea73589e917d
Create Date: 2026-07-28 18:48:58.372658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f531c82942f5'
down_revision: Union[str, Sequence[str], None] = 'ea73589e917d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "encounter",
        sa.Column(
            "workflow_status",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="awaiting_vitals",   # ← this backfills existing rows
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounter', 'workflow_status')
    # ### end Alembic commands ###
